# Generated by Django 4.2.4 on 2024-01-15 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followstatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Following_M2M',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
